name: 'Pinata Unpin Content'
description: 'Get a list of pinned content and unpin those content'
inputs:
  pinataKey:
    description: "Pinata Key"
    required: true
  pinataSecret: 
    description: "Pinata Secret"
    required: true
  pinName:
    description: 'Pin Name in metadata'
    required: true
  offset:
    description: 'List Pin Page Offset'
    required: true
outputs:
  cids:
    description: 'A list of unpinned CIDs'
runs:
  using: 'node16'
  main: 'index.js'